### PR TITLE
add michaelsFunction index.js

### PR DESCRIPTION
**Pull request by mz106**

### CODE REVIEW

**Review by hsnadrs — CHANGES_REQUESTED** [review]
good

**Review by cjsutcliffe — COMMENTED** [review]
Lovely stuff

**Review by mz106 — COMMENTED** [review]
Aisling, I have made the changes.

**Comment by mmccart3** [comment]
nice function

**Review by coopsie — APPROVED** [review]
all good

**Review by hsnadrs — APPROVED** [review]

**Comment by mz106** [comment]
All good, thanks team!

**Comment by hinasuleman** [comment]
Brilliant!

**Pull request merged**
